# Generated by Django 2.1.14 on 2020-03-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='count_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(default=0)),
                ('total_recovered', models.IntegerField(default=0)),
                ('total_active', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField(default=0)),
                ('total_delta', models.IntegerField(default=0)),
                ('counter', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='place_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=250)),
                ('place_name', models.CharField(max_length=250)),
                ('place_count', models.IntegerField(default=0)),
                ('counter', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='state_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=250)),
                ('state_count', models.IntegerField(default=0)),
                ('active_count', models.IntegerField(default=0)),
                ('recovered_count', models.IntegerField(default=0)),
                ('deaths_count', models.IntegerField(default=0)),
                ('delta', models.IntegerField(default=0)),
                ('counter', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
