# Generated by Django 2.1.14 on 2020-03-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place_table',
            name='delta_count',
            field=models.IntegerField(default=0),
        ),
    ]
