# Generated by Django 2.1.14 on 2020-04-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_place_table_delta_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_table',
            name='counter',
        ),
    ]
