# Generated by Django 2.1.14 on 2020-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200329_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='count_table',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count_table',
            name='total_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count_table',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count_table',
            name='total_recovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state_table',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
