# Generated by Django 2.1.14 on 2020-04-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_place_table_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count_table',
            old_name='counter',
            new_name='total_world_count',
        ),
        migrations.RemoveField(
            model_name='place_table',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='state_table',
            name='counter',
        ),
        migrations.AddField(
            model_name='count_table',
            name='total_world_count_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count_table',
            name='total_world_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='count_table',
            name='total_world_deaths_delta',
            field=models.IntegerField(default=0),
        ),
    ]
