# Generated by Django 2.1.14 on 2020-04-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200403_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count_table',
            old_name='total_world_count',
            new_name='counter',
        ),
    ]
