# Generated by Django 2.1.14 on 2020-04-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200403_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='count_table',
            old_name='counter',
            new_name='total_world_count',
        ),
    ]
