# Generated by Django 2.1.14 on 2020-04-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='qtext',
            field=models.CharField(max_length=250),
        ),
    ]
