# Generated by Django 2.1.14 on 2020-04-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200405_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='qtext',
            field=models.TextField(),
        ),
    ]
